const actions = {

    // COMMON
    COMMON_SET_USER_DATA: 'COMMON_SET_USER_DATA',
    COMMON_SET_TITLE: 'COMMON_SET_TITLE',

    // ORDERS
    ORDERS_SET_DATA: 'ORDERS_SET_DATA',
    ORDERS_SET_LOADING: 'ORDERS_SET_LOADING',
    ORDERS_SET_SEARCH: 'ORDERS_SET_SEARCH',
    ORDERS_SET_ONLY_ACTIVE: 'ORDERS_SET_ONLY_ACTIVE',
    ORDERS_SET_ONLY_MY: 'ORDERS_SET_ONLY_MY',

};

export default actions;
