const actions = {

    // COMMON
    COMMON_SET_USER_DATA: 'COMMON_SET_USER_DATA',
    COMMON_SET_TITLE: 'COMMON_SET_TITLE',

    // ORDERS
    ORDERS_SET_DATA: 'ORDERS_SET_DATA',
    ORDERS_SET_LOADING: 'ORDERS_SET_LOADING',
    ORDERS_SET_SEARCH: 'ORDERS_SET_SEARCH',
    ORDERS_SET_ONLY_ACTIVE: 'ORDERS_SET_ONLY_ACTIVE',
    ORDERS_SET_ONLY_MY: 'ORDERS_SET_ONLY_MY',

    // ORDER
    ORDER_SET_DATA: 'ORDER_SET_DATA',
    ORDER_SET_LOADING: 'ORDER_SET_LOADING',
    DIST_SET_LOADING: 'DIST_SET_LOADING',
    DIST_SET_DATA: 'DIST_SET_DATA',
    AOI_SET_LOADING: 'AOI_SET_LOADING',
    AOI_SET_DATA: 'AOI_SET_DATA',

    // CUSTOMERS
    CUSTOMERS_SET_DATA: 'CUSTOMERS_SET_DATA',
    CUSTOMERS_SET_LOADING: 'CUSTOMERS_SET_LOADING',
    CUSTOMERS_SET_SEARCH: 'CUSTOMERS_SET_SEARCH',
    CUSTOMERS_SET_DEFAULT: 'CUSTOMERS_SET_DEFAULT',
    CUSTOMER_SET_LOADING: 'CUSTOMER_SET_LOADING',
    CUSTOMER_SET_DATA: 'CUSTOMER_SET_DATA',
    CUSTOMER_SET_DISABLED: 'CUSTOMER_SET_DISABLED'

};

export default actions;
