const actions = {

    // COMMON
    COMMON_SET_DATA: 'COMMON_SET_DATA',
    COMMON_SET_TITLE: 'COMMON_SET_TITLE',
    COMMON_SET_MODULE_NAME: 'COMMON_SET_MODULE_NAME',

    // STATISTICS
    INDEX_SET_LOADING: 'INDEX_SET_LOADING',
    INDEX_SET_DATA: 'INDEX_SET_DATA',

    // STATISTICS
    STATISTICS_SET_LOADING: 'STATISTICS_SET_LOADING',
    STATISTICS_SET_DATA: 'STATISTICS_SET_DATA',

    // STATCHART
    STATCHART_SET_LOADING: 'STATCHART_SET_LOADING',
    STATCHART_SET_DATA: 'STATCHART_SET_DATA'

};

export default actions;
